# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: builder-base
      context: builder-base
      kaniko:
        buildArgs:
          VERSION: "${VERSION}"
          SCM_REF: "${SCM_REF}"
          BUILD_TAG: "${BUILD_TAG}"
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-java8
      context: builder-java
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
          JDK_VERSION: "1.8.0"
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-java11
      context: builder-java
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
          JDK_VERSION: "11"
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-nodejs
      context: builder-nodejs
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-nuxeo1010
      context: builder-nuxeo1010
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-python36
      context: builder-python36
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
    - image: builder-python37
      context: builder-python37
      kaniko:
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/${ORG}/builder-base:${VERSION}
        buildContext:
          localDir: {}
        cache:
          repo: ${DOCKER_REGISTRY}/${ORG}/cache
  cluster:
    namespace: ai
    pullSecretName: kaniko-secret
    dockerConfig:
      secretName: jenkins-docker-cfg
test:
# Requires Skaffold 1.9+
#  - image: builder-python36
#    structureTests:
#      - './builder-python36/test/*'
#  - image: builder-python37
#    structureTests:
#      - './builder-python37/test/*'
